version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatgpt_clone
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
